// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fast_iter
NumericMatrix fast_iter(int n, int W, NumericMatrix m, NumericVector xw, NumericVector xv);
RcppExport SEXP knapsackpackage_fast_iter(SEXP nSEXP, SEXP WSEXP, SEXP mSEXP, SEXP xwSEXP, SEXP xvSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type W(WSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xw(xwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xv(xvSEXP);
    __result = Rcpp::wrap(fast_iter(n, W, m, xw, xv));
    return __result;
END_RCPP
}
