# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_iter <- function(n, W, m, xw, xv) {
    .Call('knapsackpackage_fast_iter', PACKAGE = 'knapsackpackage', n, W, m, xw, xv)
}

